apiVersion: v1
kind: PersistentVolumeClaim # 1. Petición de volumen persistente (PVC)
metadata:
  name: patients-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment # 2. Despliegue de la Base de Datos
metadata:
  name: patients-db-deployment
spec:
  selector:
    matchLabels:
      app: patients-db
  template:
    metadata:
      labels:
        app: patients-db
    spec:
      containers:
      - name: patients-db
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: user_patients
        - name: POSTGRES_PASSWORD
          value: password_patients
        - name: POSTGRES_DB
          value: patients_db
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: patients-db-pvc
---
apiVersion: v1
kind: Service # 3. Service: Permite a los pods acceder a la DB
metadata:
  name: patients-db-service # ¡Este nombre es el que usa el microservicio en su DATABASE_URL!
spec:
  selector:
    app: patients-db
  ports:
  - port: 5432
    targetPort: 5432