name: CI/CD - Build & Push Microservices

on:
  push:
    branches:
      - main # Ejecuta el pipeline en cada push a la rama principal
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # --------------------------------------------------------------------
      # BUILD & PUSH: AUTH-SERVICE
      # --------------------------------------------------------------------
      - name: Build and Push Auth Service
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service # Carpeta donde está el Dockerfile
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest # Etiqueta con tu usuario de Docker Hub
          
      # --------------------------------------------------------------------
      # BUILD & PUSH: PATIENTS-SERVICE
      # --------------------------------------------------------------------
      - name: Build and Push Patients Service
        uses: docker/build-push-action@v5
        with:
          context: ./patients-service # Carpeta donde está el Dockerfile
          file: ./patients-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/patients-service:latest # Etiqueta con tu usuario de Docker Hub